#!/usr/bin/env python
"""
Train a Sparse Autoencoder on extracted PLM embeddings.

Usage:
    python scripts/train_sae.py \
        --embeddings_dir ../data/embeddings/esm2_8m/layer_6 \
        --save_dir ../models/sae/layer_6 \
        --activation_dim 320 \
        --dict_size 1280 \
        --steps 10000 \
        --batch_size 512 \
        --l1_penalty 0.06
"""

import os
import sys
import random

import numpy as np
import torch

# Allow running directly from the repository root, e.g.
#   python Single/single/scripts/analyze_sequence.py ...
# without `cd Single` or installing the package (the `single` package lives at
# Single/single/, two levels up from this file).
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import argparse
from pathlib import Path
from typing import Optional

from single.configs import SAEConfig, TrainingConfig, DataConfig, CheckpointConfig
from single.train.training_run import SAETrainingRun


def train_sae(
    embeddings_dir: Optional[Path] = None,
    save_dir: Optional[Path] = None,
    experiment: Optional[str] = None,
    exp_dir: Optional[Path] = None,
    source: Optional[str] = None,
    layer: int = 6,
    shard: Optional[int] = None,
    activation_dim: int = 320,
    dict_size: int = 1280,
    expansion_factor: int = 4,
    lr: float = 2e-4,
    steps: int = 10000,
    batch_size: int = 512,
    l1_penalty: float = 0.06,
    reconstruction_loss: str = "l2",
    warmup_steps: int = 1000,
    decay_start: int = 8000,
    resample_steps: Optional[int] = None,
    save_steps: int = 2000,
    max_ckpts_to_keep: int = 3,
    seed: int = 42,
    resume_from: Optional[Path] = None,
):
    from single.paths import resolve_experiment

    # Resolve experiment dir first (needed for default embeddings/save paths).
    if experiment is None and exp_dir is None:
        raise ValueError("Must provide either --experiment or --exp_dir")
    exp = resolve_experiment(exp_dir=exp_dir, name=experiment, source=source)
    print(f"Experiment dir: {exp.dir}")

    # Seed all random sources for reproducible SAE init and dead-neuron resampling.
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # Prefer explicit embeddings_dir; else infer Outputs/<exp>/embeddings/layer_<N>
    # (which contains ALL shards for that layer — shard_0..shard_N-1).
    if embeddings_dir is None:
        embeddings_dir = exp.embeddings_dir(layer=layer)
        print(f"Using embeddings from: {embeddings_dir}")

    # Prefer explicit save_dir (legacy); else route into the experiment dir.
    if save_dir is None:
        save_dir = exp.sae_dir
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    data_cfg = DataConfig(
        plm_embd_dir=embeddings_dir,
        shard=shard,
    )
    if shard is not None:
        print(f"Using only shard {shard}")
    else:
        print("Using all shards")

    sae_cfg = SAEConfig(
        activation_dim=activation_dim,
        dict_size=dict_size,
        expansion_factor=expansion_factor,
    )

    train_cfg = TrainingConfig(
        lr=lr,
        steps=steps,
        batch_size=batch_size,
        warmup_steps=warmup_steps,
        decay_start=decay_start,
        l1_penalty=l1_penalty,
        reconstruction_loss=reconstruction_loss,
        resample_steps=resample_steps,
        seed=seed,
    )

    checkpoint_cfg = CheckpointConfig(
        save_dir=save_dir,
        save_steps=save_steps,
        max_ckpts_to_keep=max_ckpts_to_keep,
    )

    print("=" * 60)
    print("SAE Training Configuration")
    print("=" * 60)
    print(f"Embeddings: {embeddings_dir}")
    print(f"Model: {activation_dim}D → {dict_size} features")
    print(f"Steps: {steps}, Batch: {batch_size}, LR: {lr:.1e}")
    print(f"L1 penalty: {l1_penalty}")
    print(f"Reconstruction loss: {reconstruction_loss}")
    print(f"Save to: {save_dir}")
    print()

    training_run = SAETrainingRun.from_configs(
        data_cfg=data_cfg,
        sae_cfg=sae_cfg,
        train_cfg=train_cfg,
        checkpoint_cfg=checkpoint_cfg,
    )

    if resume_from is not None:
        training_run.resume_from_checkpoint(resume_from)

    training_run.run()

    # Invalidate any stale normalized checkpoint from a previous training run.
    # load_sae prefers model_normalized.pt; if it's left over from an older model
    # (different dict_size, etc.), downstream scripts would silently load the
    # wrong weights. Delete it so it gets regenerated for the new model.
    stale_norm = Path(save_dir) / "model_normalized.pt"
    if stale_norm.exists():
        stale_norm.unlink()
        print(f"Removed stale {stale_norm} (will be regenerated by analyze_features)")

    print(f"\nModel saved to {save_dir / 'model.pt'}")
    print("Done!")


def main(argv=None):
    parser = argparse.ArgumentParser(description="Train SAE on PLM embeddings")
    parser.add_argument("--embeddings_dir", type=Path, default=None,
                        help="Embeddings dir to train on (default: "
                             "Outputs/<experiment>/embeddings/layer_<N>, all shards)")
    parser.add_argument("--source", type=str, default=None,
                        help="Data-source id; nests outputs under Outputs/<experiment>/<source> (default: flat)")
    parser.add_argument("--experiment", type=str, default=None,
                        help="Experiment name; routes outputs into Outputs/<experiment>/")
    parser.add_argument("--exp_dir", type=Path, default=None,
                        help="Reuse an existing experiment directory")
    parser.add_argument("--save_dir", type=Path, default=None,
                        help="Explicit save dir (overrides experiment routing)")
    parser.add_argument("--layer", type=int, default=6,
                        help="Embedding layer to train on (for default embeddings_dir)")
    parser.add_argument("--shard", type=int, default=None,
                        help="Train on only one shard (default: use all shards)")
    parser.add_argument("--activation_dim", type=int, default=320)
    parser.add_argument("--dict_size", type=int, default=1280)
    parser.add_argument("--expansion_factor", type=int, default=4)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--steps", type=int, default=10000)
    parser.add_argument("--batch_size", type=int, default=512)
    parser.add_argument("--l1_penalty", type=float, default=0.06)
    parser.add_argument("--reconstruction_loss", choices=("l2", "mse"), default="l2",
                        help="Reconstruction loss: legacy unsquared L2 or MSE")
    parser.add_argument("--warmup_steps", type=int, default=1000)
    parser.add_argument("--decay_start", type=int, default=8000)
    parser.add_argument("--resample_steps", type=int, default=None,
                        help="Reinitialize dead neurons every N steps (reduces dead_pct)")
    parser.add_argument("--save_steps", type=int, default=2000)
    parser.add_argument("--max_ckpts_to_keep", type=int, default=3,
                        help="Keep only the newest N step checkpoints (0 = keep all)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--resume_from", type=Path, default=None)
    args = parser.parse_args(argv)
    train_sae(**{k: v for k, v in vars(args).items() if v is not None})


if __name__ == "__main__":
    main()
